blog/urls.py
from django.urls import path

from . import views

app_name = "blog"
urlpatterns = [
    path("", views.home, name="home"),
    path("categories/", views.category_list, name="category_list"),
    path("categories/<int:category_id>/", views.category_detail, name="category_detail"),
    path("categories/add/", views.category_add, name="category_add"),
    path("categories/<int:category_id>/edit/", views.category_edit, name="category_edit"),

    path("posts/<int:post_id>/", views.post_detail, name="post_detail"),
    path("posts/add/<int:category_id>/", views.post_add, name="post_add"),
    path("posts/<int:post_id>/edit", views.post_edit, name="post_edit"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("blog.urls")),
]

blog/models.py
from django.db import models

class Category(models.Model):
    """Blog Category Model"""
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

class Post(models.Model):
    """Blog Post Model"""
    title = models.CharField(max_length=200)
    content = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

blog/forms.py
from django import forms

from .models import Category, Post

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']
        labels = {'name': ''}

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']
        labels = {'title': '', 'content': ''}
        widgets = {'content': forms.Textarea(attrs={'cols': 80})}

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect

from blog.forms import CategoryForm, PostForm
from blog.models import Category, Post


def home(request):
    return render(request, 'home.html')


def category_list(request):
    categories = Category.objects.order_by('date_added')
    context = {
        'categories': categories
    }
    return render(request, 'categories/category_list.html', context)


def category_detail(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    posts = category.post_set.order_by('-date_added')
    context = {
        'category': category,
        'posts': posts
    }
    return render(request, 'categories/category_detail.html', context)


def category_add(request):
    if request.method != 'POST':
        form = CategoryForm()
    else:
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('blog:category_list')

    context = {
        'form': form
    }
    return render(request, 'categories/category_add.html', context)


def category_edit(request, category_id):
    category = get_object_or_404(Category, pk=category_id)

    if request.method != 'POST':
        form = CategoryForm(instance=category)
    else:
        form = CategoryForm(instance=category, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blog:category_detail', category_id=category_id)

    context = {
        'category': category,
        'form': form
    }
    return render(request, 'categories/category_edit.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    context = {
        'post': post
    }
    return render(request, 'posts/post_detail.html', context)


def post_add(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    if request.method != 'POST':
        form = PostForm()
    else:
        form = PostForm(request.POST)
        if form.is_valid():
            post_add = form.save(commit=False)
            post_add.category = category
            post_add.save()
            return redirect('blog:category_detail', category_id=category_id)

    context = {
        'category': category,
        'form': form
    }
    return render(request, 'posts/post_add.html', context)


def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    category = post.category

    if request.method != 'POST':
        form = PostForm(instance=post)
    else:
        form = PostForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blog:category_detail', category_id=category.id)

    context = {
        'post': post,
        'category': category,
        'form': form
    }
    return render(request, 'posts/post_edit.html', context)

blog/templates/base.html
<p>
    <a href="{% url 'blog:home' %}">Home</a> -
    <a href="{% url 'blog:category_list' %}">Categories</a>
</p>

{% block content %}{% endblock %}

blog/templates/categories/category_add.html
{% extends "base.html" %}

{% block content %}
    <p>Add a new category:</p>

    <form action="{% url 'blog:category_add' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add category</button>
    </form>
{% endblock %}

blog/templates/categories/category_detail.html
{% extends "base.html" %}

{% block content %}
    <p>{{ category }}</p>
    <p><a href="{% url 'blog:category_edit' category_id=category.id %}">Edit category</a></p>

    <p>Posts:</p>

    <ul>
        {% for post in posts %}
            <li><a href="{% url 'blog:post_detail' post.id %}">{{ post }}</a></li>
        {% empty %}
            <li>Not posts have been added yet.</li>
        {% endfor %}
    </ul>

    <p><a href="{% url 'blog:post_add' category.id %}">Add new post</a></p>
{% endblock %}

blog/templates/categories/category_edit.html
{% extends "base.html" %}

{% block content %}
    <p>Edit a category:</p>

    <form action="{% url 'blog:category_edit' category_id=category.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Save category</button>
    </form>
{% endblock %}

blog/templates/categories/category_list.html
{% extends "base.html" %}

{% block content %}
    <p>Categories</p>

    <ul>
        {% for category in categories %}
            <li>
                <a href="{% url 'blog:category_detail' category.id %}">{{ category }}</a>
            </li>
        {% empty %}
            <li>Not categories have been added yet.</li>
        {% endfor %}
    </ul>

    <a href="{% url 'blog:category_add' %}">Add new category</a>
{% endblock %}

blog/templates/home.html
{% extends "base.html" %}

{% block content %}
    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
{% endblock %}

blog/templates/posts/post_add.html
{% extends "base.html" %}

{% block content %}
    <p><a href="{% url 'blog:category_detail' category_id=category.id %}">{{ category }}</a></p>

    <p>Add a new post:</p>

    <form action="{% url 'blog:post_add' category.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add post</button>
    </form>
{% endblock %}

blog/templates/posts/post_detail.html
{% extends "base.html" %}

{% block content %}
    <p><a href="{% url 'blog:category_detail' category_id=post.category.id %}">{{ post.category }}</a></p>

    <p>Post: {{ post }}</p>

    <p>{{ post.content }}</p>

    <p>{{ post.date_added|date:'d M, Y H:i'}}</p>

    <p><a href="{% url 'blog:post_edit' post_id=post.id %}">Edit post</a></p>
{% endblock %}

blog/templates/posts/post_edit.html
{% extends "base.html" %}

{% block content %}
    <p><a href="{% url 'blog:category_detail' category_id=category.id %}">{{ category }}</a></p>

    <p>Edit a post:</p>

    <form action="{% url 'blog:post_edit' post.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Save post</button>
    </form>
{% endblock %}